# Generated by Django 4.0 on 2022-03-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway',
            field=models.CharField(default='Gateway', max_length=100),
        ),
    ]
